server:
  port: 9193

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/himanshu-rana1/microservice-example-config-server
          clone-on-start: true